---
title: Exemple de rapport `Rmarkdown` en sortie d'un pipeline `targets`

# Use letters for affiliations, numbers to show equal authorship (if applicable) and to indicate the corresponding author
author:
  - name: Alexandre Martineau
    affiliation: a
  - name: Clara Prévosto
    affiliation: a
  - name: Élisabeth Roy
    affiliation: a
  - name: Laura Béland
    affiliation: a
  - name: Laurence Boum
    affiliation: a

address:
  - code: a
    address: Université de Sherbrooke, Départment de biologie, 2500 Boulevard de l'Université, Sherbrooke, Québec, J1K 2R1

abstract: |
  Eurytus auris. Gerunt transierant miserorum latet; nisi cum, et circuitu nubila
  coloribus adventus divesque. Loca partibus breve et unum maior stellis inpia et
  luporum. Arces alter sceptra, nutricisque petentem mentes nuntia Lycaon solet,
  solitaque signa moriensque pontus, dux? Corpora testataque, novo tumidum. Eurytus auris.
  Gerunt transierant miserorum latet; nisi cum, et circuitu nubila coloribus adventus divesque. 
  Loca partibus breve et unum maior stellis inpia et luporum. Arces alter sceptra, nutricisque 
  petentem mentes nuntia Lycaon solet, solitaque signa moriensque pontus, dux? Corpora 
  testataque, novo tumidum.

keywords:
  - Mot-clé
  - Mot-clé
  - Optionel
  - Optionel
  - Optionel

## must be one of: pnasresearcharticle (usual two-column layout), pnasmathematics (one column layout), or pnasinvited (invited submissions only)
pnas_type: pnasresearcharticle

bibliography: pnas-sample.bib
csl: pnas.csl

## change to true to add optional line numbering
lineno: false

output: rticles::pnas_article
---

# Introduction
**Voici un exemple de citation @berard1994embedding, et en voici deux autres [@berard1994embedding;@belkin2002using;@coifman2005geometric].** 
Le but de ce rapport est de voir si le réseau de collaboration des étudiant du cours de BIO500 de l'université de Sherbrooke à l'hiver 2022 ont les mêmes propriétés qu'un réseau écologique typique d'un environnement naturel. Pour le savoir, quelques question furent possées et répondues dans ce rapport. Les questions étant de savoir s'il existe une correlation entre le nombre de liens des étudiants entre eux et leur centralité par rapport au réseau de liens des étudiants. Par la suite, le calcul du Bacon number d'un des étudiants pour calculer la distance entre les étudiants. 

# Méthode

La méthode utilisée pour la lecture, le nettoyage, l'injection des données et l'analyse des différentes données fut l'utilisation de code dans R version 4.1.3 et l'utilisation de GitHub pour le partage des données et le stockages.

# Résultats

La figure 1 montre la position des étudiants en fonction du nombre de lien les un par rapport aux autres. 
La figure 2 représente la corrélation entre la centralité et le nombre de lien des étudiants. La corrélation entre ces deux facteurs n'est pas significative, car la relation n'est pas linéaire, car la corrélation a un P-value de 0,2493.
La figure 3 représente le degré de séparation par rapport à un individue. Dans ce cas si, en prennant Élisabeth Roy comme individue, la fréquence est plus élevé plus le degré de séparation est élevé.

# Discussion

Per recepto pugnes. Soror est adiit nusquam, in arserunt nondum tempore
bracchia. Pater tempora limen. Falcata parentibus dolor et vobis aranea! Auro
modo deos, tunicis praebita, nimium luctataque nec, vix densumque proles
fluitare ipse per, solent?
Pondera abrumpit cum quaeque iuris. Tinxit fudit clipei non Acheloe accipe
dextramque, lacrimantem de quid frustra omnes. Indigenae exta quamque modo meae,
detur idem curas prope erat. Liquefaciunt perdis quoque pharetraque est nunc non
pondus Pyramus in Latona ferrum: nubibus renoventur! Fallacia sonuit Proreus,
aurora: omen cur a moenia ore ego narret, ego. Morae dixit non longum corpore dicentem cognovit Epidauria abit, messes terraeque extremo: utque. Dixi mea, exsiluisse dedit; Venus lenita radiantia partes quo populos ensis: circumdet. Et rapta numina, non Pylos nostras, qui
primum omnes fabrilis et utraque mutant cacumine aequoris quinque.

Ligavit cetera et infelix nescius, sinu timorem admonitu ferrove exspectatas
fuerant pulcherrime, mea sonum! Formae munera, est trahendo regem supplice.
Verba lacrimis gradus, verbis iam tempore aratri sed, at imagine momordit. Teque
esse, ante pariter desere in quae: illa socium inque meae: et ipso canos:
peteretis? Temptanda Daedalus et palmis incumbere tempora ambit.

Lorem markdownum et est, an mane luctu iugis ignibus in hostia peragit dum eadem
equinis, par gradus ubi! Silet canities sine dedecet, fides virum capro:
loquuntur ante. Celeres condi aut latet pedibusque laetus posuere pollue est hoc
terra, nutricisque flava. Eurytus auris. Gerunt transierant miserorum latet; nisi cum, et circuitu nubila coloribus adventus divesque. Loca partibus breve et unum maior stellis inpia et
luporum. Arces alter sceptra, nutricisque petentem mentes nuntia Lycaon solet,
solitaque signa moriensque pontus, dux? Corpora testataque, novo tumidum. Eurytus auris. Gerunt transierant miserorum latet; nisi cum, et circuitu nubilacoloribus adventus divesque. Loca partibus breve et unum maior stellis inpia etluporum. Arces alter sceptra, nutricisque petentem mentes nuntia Lycaon solet, solitaque signa moriensque pontus, dux? Corpora testataque, novo tumidum.

# Conclusion

Ligavit cetera et infelix nescius, sinu timorem admonitu ferrove exspectatas
fuerant pulcherrime, mea sonum! Formae munera, est trahendo regem supplice.
Verba lacrimis gradus, verbis iam tempore aratri sed, at imagine momordit. Teque
esse, ante pariter desere in quae: illa socium inque meae: et ipso canos:
peteretis? Temptanda Daedalus et palmis incumbere tempora ambit.

\newpage
# Bibliographie{-}
